name: Validate 'setup-grpc'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: 0 0 * * *

jobs:
  setup-versions:
    name: Setup ${{ matrix.grpc }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        grpc: [1.30.0]
    steps:
      - uses: actions/checkout@v2
      - name: Setup gRPC
        uses: ./
        with:
          grpc-version: ${{ matrix.grpc }}
      - name: Verify gRPC
        run: |
          cd grpc/examples/cpp/helloworld
          mkdir build
          cd build
          cmake ../..
          make -j 2
        shell: bash

